# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c7f7ae7b1396148633224c781c80915b32794e41cb95016202fb169ab8a3e6e39c5d5e6c1663582434b704e88c6c1d464aeb10700b85c8496ffd5be03ad850cf

test:
  secret_key_base: 6b5a4e87b2a00b618cb7f5bb980fa5759984a4d536ded0c6bc732969dfaac3e4bd867a32183244cb9381dd19b4fc4f12f6824a622b3391fa1a0cd11258c9e384

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
